industry_materiality_dict = {
    "Advertising & Marketing": {
        "material": ["hc_eedi", "sc_cp", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Aerospace & Defense": {
        "material": [
            "bmi_mse",
            "e_em",
            "e_whmm",
            "lg_be",
            "sc_ds",
            "sc_pqs",
            "bmi_pdlm",
        ],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Agricultural Products": {
        "material": [
            "bmi_mse",
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_wwm",
            "hc_ehs",
            "sc_pqs",
        ],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_whmm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Air Freight & Logistics": {
        "material": ["bmi_scm", "e_ghge", "hc_ehs", "hc_lp", "lg_cirm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "lg_be",
            "lg_cb",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Airlines": {
        "material": ["e_ghge", "hc_lp", "lg_cb", "lg_cirm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Alcoholic Beverages": {
        "material": ["bmi_mse", "bmi_scm", "e_em", "e_wwm", "sc_sppl", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Apparel, Accessories & Footwear": {
        "material": ["bmi_mse", "bmi_scm", "sc_pqs"],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Appliance Manufacturing": {
        "material": ["sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Asset Management & Custody Activities": {
        "material": ["hc_eedi", "lg_be", "lg_srm", "sc_sppl", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Automobiles": {
        "material": ["bmi_mse", "hc_lp", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Auto Parts": {
        "material": ["bmi_mse", "e_em", "e_whmm", "lg_cb", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Biofuels": {
        "material": ["bmi_scm", "e_wwm", "lg_cirm", "lg_mlre", "bmi_pdlm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
        ],
    },
    "Biotechnology & Pharmaceuticals": {
        "material": [
            "bmi_scm",
            "hc_eedi",
            "lg_be",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_ds",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Building Products & Furnishings": {
        "material": ["bmi_scm", "e_em", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Car Rental & Leasing": {
        "material": ["sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Casinos & Gaming": {
        "material": ["e_em", "hc_ehs", "lg_be", "sc_cw"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Chemicals": {
        "material": [
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_cirm",
            "lg_mlre",
            "sc_hrcr",
            "bmi_pdlm",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
        ],
    },
    "Coal Operations": {
        "material": [
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "sc_hrcr",
            "bmi_bmr",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "hc_eedi",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Commercial Banks": {
        "material": ["lg_be", "lg_srm", "sc_aa", "sc_ds", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "sc_cp",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Construction Materials": {
        "material": [
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_cb",
            "bmi_pdlm",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
        ],
    },
    "Consumer Finance": {
        "material": ["sc_cp", "sc_ds", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Containers & Packaging": {
        "material": [
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "sc_pqs",
            "bmi_pdlm",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
        ],
    },
    "Cruise Lines": {
        "material": ["e_ei", "e_ghge", "hc_ehs", "hc_lp", "lg_cirm", "sc_pqs", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "lg_be",
            "lg_cb",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Drug Retailers": {
        "material": ["e_em", "sc_cw", "sc_ds", "sc_pqs"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "E-Commerce": {
        "material": ["e_em", "hc_eedi", "sc_cp", "sc_ds", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Education": {
        "material": ["sc_cw", "sc_ds", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Electrical & Electronic Equipment": {
        "material": ["bmi_mse", "e_em", "e_whmm", "lg_be", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Electric Utilities & Power Generators": {
        "material": [
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_cirm",
            "lg_srm",
            "sc_aa",
            "bmi_bmr",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_mlre",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
        ],
    },
    "Electronic Manufacturing Services & Original Design Manufacturing": {
        "material": ["bmi_mse", "e_whmm", "e_wwm", "hc_ehs", "hc_lp", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "hc_eedi",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Engineering & Construction Services": {
        "material": ["e_ei", "hc_ehs", "lg_be", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Food Retailers & Distributors": {
        "material": [
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_whmm",
            "hc_lp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_hrcr",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Forestry Management": {
        "material": ["bmi_picc", "e_ei", "sc_hrcr"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Fuel Cells & Industrial Batteries": {
        "material": ["bmi_mse", "e_em", "hc_ehs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Gas Utilities & Distributors": {
        "material": ["lg_cirm", "sc_aa", "bmi_bmr"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Hardware": {
        "material": ["bmi_mse", "bmi_scm", "hc_eedi", "sc_ds", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Health Care Delivery": {
        "material": [
            "bmi_picc",
            "e_em",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "sc_aa",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_wwm",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_hrcr",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Health Care Distributors": {
        "material": ["e_ghge", "lg_be", "sc_cw", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Home Builders": {
        "material": ["e_ei", "hc_ehs", "bmi_bmr", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "e_aq",
        ],
    },
    "Hotels & Lodging": {
        "material": ["bmi_picc", "e_ei", "e_em", "e_wwm", "hc_lp"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Household & Personal Products": {
        "material": ["bmi_scm", "e_wwm", "sc_pqs", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Industrial Machinery & Goods": {
        "material": ["bmi_mse", "e_em", "hc_ehs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Insurance": {
        "material": ["bmi_picc", "lg_srm", "sc_sppl", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Internet Media & Services": {
        "material": ["e_em", "hc_eedi", "lg_cb", "sc_cp", "sc_ds"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Investment Banking & Brokerage": {
        "material": ["hc_eedi", "lg_be", "lg_srm", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Iron & Steel Producers": {
        "material": ["bmi_scm", "e_em", "e_ghge", "e_whmm", "e_wwm", "hc_ehs", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Leisure Facilities": {
        "material": ["e_em", "hc_ehs", "sc_pqs"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Managed Care": {
        "material": ["bmi_picc", "sc_aa", "sc_cw", "sc_ds", "sc_pqs"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Marine Transportation": {
        "material": ["e_ei", "e_ghge", "hc_ehs", "lg_be", "lg_cirm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_cb",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Meat, Poultry & Dairy": {
        "material": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_wwm",
            "hc_ehs",
            "sc_cw",
            "sc_pqs",
            "bmi_pdlm",
        ],
        "immaterial": [
            "bmi_picc",
            "e_whmm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Media & Entertainment": {
        "material": ["lg_cb", "sc_cw", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Medical Equipment & Supplies": {
        "material": ["bmi_scm", "lg_be", "sc_aa", "sc_pqs", "sc_sppl", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Metals & Mining": {
        "material": [
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "sc_hrcr",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "hc_eedi",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Mortgage Finance": {
        "material": ["bmi_picc", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Multiline and Specialty Retailers & Distributors": {
        "material": ["e_em", "hc_eedi", "hc_lp", "sc_ds", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Non-Alcoholic Beverages": {
        "material": [
            "bmi_mse",
            "bmi_scm",
            "e_em",
            "e_ghge",
            "e_wwm",
            "sc_cw",
            "sc_sppl",
            "bmi_pdlm",
        ],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Oil & Gas – Exploration & Production": {
        "material": [
            "e_ei",
            "e_ghge",
            "e_wwm",
            "hc_ehs",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "sc_hrcr",
            "bmi_bmr",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_whmm",
            "hc_eedi",
            "hc_lp",
            "lg_cb",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
        ],
    },
    "Oil & Gas – Midstream": {
        "material": ["e_ei", "e_ghge", "lg_cb", "lg_cirm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Oil & Gas – Refining & Marketing": {
        "material": [
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "bmi_pdlm",
            "e_aq",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
        ],
    },
    "Oil & Gas – Services": {
        "material": [
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
        ],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_em",
            "hc_eedi",
            "hc_lp",
            "lg_cb",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Processed Foods": {
        "material": [
            "bmi_mse",
            "bmi_scm",
            "e_em",
            "e_wwm",
            "sc_cw",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
        ],
        "immaterial": [
            "bmi_picc",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Professional & Commercial Services": {
        "material": ["hc_eedi", "lg_be", "sc_ds"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Pulp & Paper Products": {
        "material": ["bmi_scm", "e_em", "e_ghge", "e_wwm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Rail Transportation": {
        "material": ["e_ghge", "hc_ehs", "lg_cb", "lg_cirm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Real Estate": {
        "material": ["bmi_picc", "e_em", "e_wwm", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Real Estate Services": {
        "material": ["lg_be", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Restaurants": {
        "material": ["bmi_scm", "e_em", "e_whmm", "e_wwm", "hc_lp", "sc_cw", "sc_pqs"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_ghge",
            "hc_eedi",
            "hc_ehs",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Road Transportation": {
        "material": ["e_ghge", "hc_ehs", "lg_cirm", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
        ],
    },
    "Security & Commodity Exchanges": {
        "material": ["lg_be", "lg_srm", "bmi_pdlm"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Semiconductors": {
        "material": [
            "bmi_mse",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "lg_cb",
            "bmi_pdlm",
        ],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Software & IT Services": {
        "material": ["e_em", "hc_eedi", "lg_cb", "lg_srm", "sc_cp", "sc_ds"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Solar Technology & Project Developers": {
        "material": ["bmi_mse", "e_ei", "e_em", "e_whmm", "e_wwm", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ghge",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
    "Telecommunication Services": {
        "material": ["bmi_mse", "e_em", "lg_cb", "lg_srm", "sc_cp", "sc_ds"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cirm",
            "lg_mlre",
            "sc_aa",
            "sc_cw",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Tobacco": {
        "material": ["sc_cw", "sc_sppl"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Toys & Sporting Goods": {
        "material": ["bmi_scm", "sc_pqs"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_bmr",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Waste Management": {
        "material": ["e_ghge", "e_whmm", "hc_ehs", "hc_lp", "bmi_bmr", "e_aq"],
        "immaterial": [
            "bmi_mse",
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_wwm",
            "hc_eedi",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_pdlm",
        ],
    },
    "Water Utilities & Services": {
        "material": [
            "bmi_mse",
            "bmi_picc",
            "e_em",
            "e_wwm",
            "sc_aa",
            "sc_pqs",
            "bmi_bmr",
        ],
        "immaterial": [
            "bmi_scm",
            "e_ei",
            "e_ghge",
            "e_whmm",
            "hc_eedi",
            "hc_ehs",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_sppl",
            "bmi_pdlm",
            "e_aq",
        ],
    },
    "Wind Technology & Project Developers": {
        "material": ["bmi_mse", "hc_ehs", "bmi_pdlm"],
        "immaterial": [
            "bmi_picc",
            "bmi_scm",
            "e_ei",
            "e_em",
            "e_ghge",
            "e_whmm",
            "e_wwm",
            "hc_eedi",
            "hc_lp",
            "lg_be",
            "lg_cb",
            "lg_cirm",
            "lg_mlre",
            "lg_srm",
            "sc_aa",
            "sc_cp",
            "sc_cw",
            "sc_ds",
            "sc_hrcr",
            "sc_pqs",
            "sc_sppl",
            "bmi_bmr",
            "e_aq",
        ],
    },
}
